backend:
  name: github
  repo: Nderim1/livotex-gatsby
  branch: main

# local_backend: true

media_folder: static/assets
public_folder: /assets
collections:
  - name: images
    extension: json
    label: Images
    folder: content/images
    file: content/images/index.json
    create: true
    fields:
      - { name: path, label: Path, widget: image }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: markdown }
  - name: about
    label: About
    extension: json
    folder: content/about
    file: content/about/index.json
    create: false
    fields:
      - { name: title, label: Title, widget: string}
      - { name: description, label: Description, widget: markdown}
  - name: main
    label: Website title
    extension: json
    folder: content/main
    file: content/main/index.json
    create: false
    fields:
      - { name: title, label: Title, widget: string}
      - { name: paragraph, label: Paragraph, widget: text}