backend:
  name: test-repo
  # repo: Nderim1/livotex-gatsby
  # branch: main
  # base_url: https://livotex.netlify.app/

# local_backend: true

media_folder: static/assets
public_folder: /assets
collections:
  - name: images
    label: Images
    folder: content/images
    create: true
    fields:
      - { name: path, label: Path, widget: image }
      - { name: title, label: Title, widget: string }
      - { name: description, label: Description, widget: markdown }
  - name: description
    label: Description
    folder: content/description
    create: true
    fields:
      - { name: title, label: Title, widget: string}
      - { name: description, label: Description, widget: text}